import type { Locale } from '@config/site'

/**
 * Locale negotiation for a static export, as a file the host can read.
 *
 * `src/proxy.ts` redirects an unprefixed path to a locale, and every route this
 * template generates lives under one. A static export has no middleware to run
 * that, so `npm run build:static` produces `out/en/`, `out/de/`, `out/uk/` and
 * nothing at all at `/`: the site's own front door served the 404 page, and the
 * only clue was that every internal link worked.
 *
 * `302`, not `301`. A permanent redirect off the site root is cached by
 * browsers indefinitely, so a site that later changed its primary language
 * would leave every previous visitor stranded on the old one.
 *
 * Only the root is emitted. It is tempting to add `/notes`, but the unprefixed
 * `/notes/<slug>` pages are real routes here, and they choose a locale from the
 * reader's stored preference and browser settings rather than always landing on
 * the primary one. A static rule cannot do that, and one broad enough to cover
 * the bare index risks shadowing them.
 */
export function buildRedirectsFile(primary: Locale): string {
  return [
    '# Generated by onvu. Locale negotiation for the static export: every route',
    '# lives under a locale prefix, and a static build has no middleware to send',
    `# the site root to one. Regenerated from \`locales.primary\` each build.`,
    '#',
    '# Your own rules above this block still win, in Cloudflare Pages and in',
    '# Netlify alike: the first matching rule is the one that runs.',
    `/  /${primary}/  302`,
  ].join('\n')
}
