import type { Note } from '@core/Note'

export interface LlmsTxtContext {
  siteName: string
  siteDescription: string
  /** Absolute URL of a note's HTML page. */
  noteUrl: (locale: string, slug: string) => string
  /** Absolute URL of a note's markdown mirror. */
  mirrorUrl: (locale: string, slug: string) => string
  /** Whether markdown mirrors exist to link to. */
  hasMirrors: boolean
}

export interface LocaleNotes {
  locale: string
  notes: Note[]
}

function noteLine(note: Note, locale: string, ctx: LlmsTxtContext): string {
  const href = ctx.hasMirrors ? ctx.mirrorUrl(locale, note.slug) : ctx.noteUrl(locale, note.slug)
  const summary = (note.description ?? note.preview ?? '').replace(/\s+/g, ' ').trim()
  return summary ? `- [${note.title}](${href}): ${summary}` : `- [${note.title}](${href})`
}

/**
 * `/llms.txt` — a flat map of the site for an agent that lands on the root.
 *
 * Worth being honest about what this buys: measured crawler logs show the
 * major AI crawlers overwhelmingly skip `/llms.txt` and fetch HTML instead,
 * and Google has said it doesn't support the convention. It's shipped as
 * cheap insurance and for agents a reader points at the site by hand — not
 * as a ranking lever.
 *
 * Sections are grouped by locale so an agent can pick a language without
 * fetching anything, and each entry points at the markdown mirror when one
 * exists — that being the whole reason an agent would read this file.
 */
export function buildLlmsTxt(locales: LocaleNotes[], ctx: LlmsTxtContext): string {
  const out: string[] = [`# ${ctx.siteName}`, '']
  if (ctx.siteDescription) out.push(`> ${ctx.siteDescription}`, '')

  out.push(
    ctx.hasMirrors
      ? 'Each link below is a markdown mirror of a note. Append `.md` to any note URL on this site to get the same thing; the canonical HTML page is linked at the foot of every mirror.'
      : 'Each link below is a note on this site.',
    '',
  )

  for (const { locale, notes } of locales) {
    if (notes.length === 0) continue
    out.push(`## Notes (${locale})`, '')
    for (const note of notes) out.push(noteLine(note, locale, ctx))
    out.push('')
  }

  return `${out.join('\n').trimEnd()}\n`
}

/**
 * `/llms-full.txt` — every note body inlined, for agents that would rather
 * make one request than N. Can get large; it's opt-in behind `llmsTxt.full`.
 */
export function buildLlmsFullTxt(
  locales: LocaleNotes[],
  bodies: Map<string, string>,
  ctx: LlmsTxtContext,
): string {
  const out: string[] = [`# ${ctx.siteName}`, '']
  if (ctx.siteDescription) out.push(`> ${ctx.siteDescription}`, '')
  out.push('Full text of every note on this site.', '')

  for (const { locale, notes } of locales) {
    for (const note of notes) {
      const body = bodies.get(`${locale}/${note.slug}`)
      if (!body) continue
      out.push(
        `## ${note.title}`,
        '',
        `Source: ${ctx.noteUrl(locale, note.slug)}`,
        '',
        body.trim(),
        '',
      )
    }
  }

  return `${out.join('\n').trimEnd()}\n`
}

/**
 * `_headers` for Netlify / Cloudflare Pages.
 *
 * Two jobs. `Content-Type: text/markdown` because most static hosts serve an
 * unknown extension as a download, which is exactly wrong for a file meant to
 * be read inline. And `X-Robots-Tag: noindex`, which costs nothing — Google
 * ignores markdown by its own account — while stopping the mirrors competing
 * with the HTML as duplicate URLs. Neither affects an agent fetching directly.
 */
export function buildHeadersFile(locales: string[]): string {
  const out = [
    '# Generated by onvu (agents.discovery.emitHeadersFile).',
    '# Markdown mirrors: served inline, kept out of human search indexes.',
    '',
  ]
  for (const locale of locales) {
    out.push(
      `/${locale}/notes/*.md`,
      '  Content-Type: text/markdown; charset=utf-8',
      '  X-Robots-Tag: noindex',
      '',
    )
  }
  out.push('/llms.txt', '  Content-Type: text/plain; charset=utf-8', '')
  out.push('/llms-full.txt', '  Content-Type: text/plain; charset=utf-8', '')
  return out.join('\n')
}
